/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryDialog: typeof import('./components/CategoryDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    IconRender: typeof import('./components/IconRender.vue')['default']
    ImportExport: typeof import('./components/ImportExport.vue')['default']
    PromptCard: typeof import('./components/PromptCard.vue')['default']
    PromptEditor: typeof import('./components/PromptEditor.vue')['default']
    StatsView: typeof import('./components/StatsView.vue')['default']
    TagBadge: typeof import('./components/TagBadge.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    ToastNotify: typeof import('./components/ToastNotify.vue')['default']
  }
}
